apiVersion: podsnapshot.gke.io/v1alpha1
kind: PodSnapshotStorageConfig
metadata:
  name: barkland-storage-config
  namespace: barkland
spec:
  snapshotStorageConfig:
    gcs:
      bucket: "$SNAPSHOT_BUCKET_NAME"
---
apiVersion: podsnapshot.gke.io/v1alpha1
kind: PodSnapshotPolicy
metadata:
  name: barkland-snapshot-policy
  namespace: barkland
spec:
  storageConfigName: barkland-storage-config
  triggerConfig:
    type: manual
  selector:
    matchLabels:
      app: barking-dog # Matches the Sandbox Claim template!
