apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxWarmPool
metadata:
  name: dog-agent-warmpool
  namespace: ${NAMESPACE}
spec:
  replicas: ${WARMPOOL_REPLICAS}
  sandboxTemplateRef:
    name: dog-agent-template
